# Generated by Django 3.1 on 2020-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='gastos',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='meta',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='total_gastos',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
