# Generated by Django 3.1 on 2020-08-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_saldo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
