# Generated by Django 3.1 on 2020-08-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200821_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='total_gastos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000),
        ),
    ]
