# Generated by Django 3.1 on 2020-08-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_saldo_total_gastos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldo',
            name='total_gastos',
        ),
        migrations.AddField(
            model_name='saldo',
            name='descricao',
            field=models.TextField(default=0, max_length=40),
        ),
    ]
