# Generated by Django 3.1 on 2020-08-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200821_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='descricao',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='gastos',
            field=models.DecimalField(decimal_places=2, max_digits=10000000),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='meta',
            field=models.DecimalField(decimal_places=2, max_digits=10000000),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10000000),
        ),
    ]
