# Generated by Django 3.1 on 2020-08-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200821_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='descricao',
            field=models.TextField(default='sem descrição', max_length=4),
        ),
    ]
