# Generated by Django 3.1 on 2020-08-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200821_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='descricao',
            field=models.TextField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='gastos',
            field=models.DecimalField(decimal_places=2, max_digits=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='meta',
            field=models.DecimalField(decimal_places=2, max_digits=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10000000, null=True),
        ),
    ]
