# Generated by Django 3.1 on 2020-08-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200821_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='descricao',
            field=models.TextField(default=' ', max_length=40, null=True),
        ),
    ]
