# Generated by Django 3.1 on 2020-08-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200821_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='gastos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000000),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='meta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000000),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000000),
        ),
    ]
