# Generated by Django 3.1 on 2020-09-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200826_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='total_gastos',
            field=models.DecimalField(decimal_places=2, max_digits=10000000, null=True),
        ),
    ]
