# Generated by Django 3.1 on 2020-08-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200826_1359'),
        ('accounts', '0013_auto_20200825_1908'),
    ]

    operations = [
    ]
