# Generated by Django 3.1 on 2020-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_saldo_total_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
