# Generated by Django 3.1 on 2020-09-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200902_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
